import React from 'react';

const ReportGenerator = ({ data }) => {
  const overview = data?.overview || {};
  const acoustic = data?.acousticFeatures || {};
  const classification = data?.classification || {};

  return (
    <div style={{
      background: 'rgba(26,35,50,0.7)',
      backdropFilter: 'blur(12px)',
      border: '1px solid rgba(255,255,255,0.07)',
      borderTop: '4px solid #3B82F6',
      borderRadius: '1rem',
      boxShadow: '0 4px 30px rgba(0,0,0,0.3)',
      padding: '2rem',
      marginTop: '0.5rem',
    }}>
      <h3 style={{fontSize:'1.5rem', fontWeight:700, marginBottom:'1.5rem', color:'#F3F4F6', borderBottom:'1px solid rgba(255,255,255,0.08)', paddingBottom:'1rem'}}>
        📋 Executive Diagnostic Summary
      </h3>

      <div style={{display:'flex', flexDirection:'column', gap:'1rem', color:'#9CA3AF', fontSize:'1rem', lineHeight:1.8}}>
        <p>
          The analyzed audio sample has a duration of{' '}
          <strong style={{color:'#F3F4F6'}}>{overview.audioDuration} seconds</strong>{' '}
          and contains{' '}
          <strong style={{color:'#F3F4F6'}}>{overview.speakerCount} unique speaker(s)</strong>.
        </p>

        <p>
          Acoustic analysis reveals a mean pitch of{' '}
          <strong style={{color:'#F3F4F6'}}>{acoustic.pitch_mean} Hz</strong>,{' '}
          RMS energy of{' '}
          <strong style={{color:'#F3F4F6'}}>{acoustic.rms_energy}</strong>, and a speaking rate of{' '}
          <strong style={{color:'#F3F4F6'}}>{acoustic.speaking_rate} segments/sec</strong>.{' '}
          Spectral centroid is{' '}
          <strong style={{color:'#F3F4F6'}}>{acoustic.spectral_centroid} Hz</strong>.
        </p>

        <p>
          ML diagnostic prediction: the primary speaker is a{' '}
          <strong style={{color:'#60A5FA'}}>
            {classification.gender?.prediction ?? '--'} {classification.age?.prediction ?? '--'}
          </strong>.
        </p>

        <p>
          Speech pattern classified as{' '}
          <strong style={{color: classification.speech_pattern?.prediction === 'Typical' ? '#34D399' : '#F87171'}}>
            {classification.speech_pattern?.prediction ?? '--'}
          </strong>{' '}
          with a confidence of{' '}
          <strong style={{color:'#F3F4F6'}}>{classification.speech_pattern?.confidence ?? '--'}%</strong>.{' '}
          Overall Speech Health Score:{' '}
          <strong style={{color:'#F3F4F6'}}>{overview.speechHealthScore}/100</strong>.
        </p>

        {/* Feature table */}
        <div style={{marginTop:'1rem', overflowX:'auto'}}>
          <table style={{width:'100%', borderCollapse:'collapse', fontSize:'0.875rem'}}>
            <thead>
              <tr style={{borderBottom:'1px solid rgba(255,255,255,0.1)'}}>
                {['Feature','Value'].map(h => (
                  <th key={h} style={{textAlign:'left', padding:'0.5rem 0.75rem', color:'#6B7280', textTransform:'uppercase', letterSpacing:'0.05em', fontSize:'0.75rem'}}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {[
                ['Pitch Mean', `${acoustic.pitch_mean} Hz`],
                ['Pitch Variance', acoustic.pitch_variance],
                ['RMS Energy', acoustic.rms_energy],
                ['Spectral Centroid', `${acoustic.spectral_centroid} Hz`],
                ['Spectral Bandwidth', `${acoustic.spectral_bandwidth} Hz`],
                ['Spectral Roll-off', `${acoustic.spectral_rolloff} Hz`],
                ['Zero Crossing Rate', acoustic.zero_crossing_rate],
                ['Speaking Rate', `${acoustic.speaking_rate} /sec`],
                ['Pause Duration', `${acoustic.pause_duration} sec`],
                ['Jitter (approx)', acoustic.jitter],
                ['Shimmer (approx)', acoustic.shimmer],
              ].map(([label, value], i) => (
                <tr key={i} style={{borderBottom:'1px solid rgba(255,255,255,0.04)', background: i % 2 === 0 ? 'rgba(255,255,255,0.02)' : 'transparent'}}>
                  <td style={{padding:'0.5rem 0.75rem', color:'#9CA3AF'}}>{label}</td>
                  <td style={{padding:'0.5rem 0.75rem', color:'#F3F4F6', fontFamily:'monospace'}}>{value ?? '--'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div style={{marginTop:'2rem', paddingTop:'1rem', borderTop:'1px solid rgba(255,255,255,0.06)', display:'flex', justifyContent:'space-between', fontSize:'0.75rem', color:'rgba(255,255,255,0.3)'}}>
        <span>Generated by ABLEPRO Diagnostic Engine v1.0</span>
        <span>{new Date().toLocaleDateString('en-IN', {year:'numeric',month:'long',day:'numeric'})}</span>
      </div>
    </div>
  );
};

export default ReportGenerator;
